### ISSUE TITLE
Duplicate serials on newer devices

### ISSUE THREAD

**Issue by darrylb123** [u1f35c/usb-relay-firmware#1]
I maintain the usbrelay software. I have had 2 people with the situation where they have bought multiple devices with the same serial. Makes it a bit hard to choose a particular device.
Is there any way to easily change the serial? 
How is it set in the first place?

**Comment by u1f35c** [comment]
Note I'm not the author of the code that ships with these devices; I've re-implemented it based on reverse engineering it. That said one of the things I saw was what I've called CMD_SET_SERIAL (0xfa) which takes 6 bytes of data and uses them to set the serial number. Perhaps you could implement that in your code to allow your users to update the serial number of their devices?

**Comment by darrylb123** [comment]
Is it permanent once set?

**Comment by u1f35c** [comment]
Yes, it is written to flash and read at power on - look at update_serno() called from usbFunctionWrite().

**Comment by darrylb123** [comment]
Added the capability to usbrelay, works great.
